networks:
  default:
    name: net123
    external: true

services:
  wa-api:
    image: alimustopaaop/wa-web-api:v1
    restart: unless-stopped
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
