networks:
  default:
    name: net123
    external: true

services:
  wa-api:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./wa_api_src/src/services/whatsapp.js:/app/src/services/whatsapp.js
    dns:
      - 8.8.8.8
      - 8.8.4.4
